### ISSUE TITLE
Found high level security vulnerability for websocket-extensions in BlackDuck scans

### ISSUE THREAD

**Issue by aakritidhawan** [faye/websocket-extensions-node#10]
While running BlackDuck scans for a project, found 1 High level security vulnerability for websocket-extensions version 0.1.4.
BlackDuck scan message-
![image](https://user-images.githubusercontent.com/47206558/90489713-4b4f8e80-e15b-11ea-98da-195f2a231a0f.png)

There is no newer version available for websocket-extensions to fix this issue.

**Comment by jcoglan** [comment]
As you will see if you check the security advisories on this repository, this issue has already been fixed in this package: https://github.com/faye/websocket-extensions-node/security/advisories/GHSA-g78m-2chm-r7qv.

The message you're seeing here is for the _Ruby_ version of the package, which has also fixed the issue: https://github.com/faye/websocket-extensions-ruby/security/advisories/GHSA-g6wq-qcwm-j5g2.

I've had [another report](https://github.com/faye/websocket-driver-node/pull/37#issuecomment-668753914) of Black Duck reporting this issue against the wrong package, you should probably advise the vendor that their software is raising a warning incorrectly.
