### ISSUE TITLE
Vulnerability allows Denial of Service (DoS) via Regex Backtracking

### ISSUE THREAD

**Issue by clepore** [faye/websocket-extensions-node#8]
I wasn't sure if you were aware of this: National Vulnerability DB - [CVE-2020-7663](https://nvd.nist.gov/vuln/detail/CVE-2020-7663)

Thanks and cheers!

**Comment by md-hamed** [comment]
I think this one is related to https://github.com/faye/websocket-extensions-ruby (and it was fixed in their latest version btw). The similar vulnerability related to this package is [CVE-2020-7662](https://nvd.nist.gov/vuln/detail/CVE-2020-7662) and it was already resolved in the latest version. However; for some reason, I'm getting the CVE-2020-7663 vulnerability warning in the vulnerability management tool of one of my projects. I think these might be something wrong with the vulnerabilities database.

**Comment by jcoglan** [comment]
Just to confirm: CVE-2020-7662 relates to this repository, and CVE-2020-7663 relates to the Ruby version, https://github.com/faye/websocket-extensions-ruby. Both these CVEs have been addressed in published releases. Is there another reason you were flagging this, @clepore, or should I close this issue?

**Comment by clepore** [comment]
@jcoglan , I was seeing the same issue as @md-hamed. Our security tool is flagging this as "not fixed" for this repository saying it needs to be on version `0.1.5` or greater to be "fixed".

If this is fixed in 0.1.4, I might have to file an inconsistency with the tool and you can close this. Can you confirm, please?

**Comment by jcoglan** [comment]
@clepore That's ok, I was wondering whether your reporting tool is confusing this repo with https://github.com/faye/websocket-extensions-ruby, since both repos contain a package with the same name, but that repo is a Ruby package while this one is for Node.js.

Just to spell this out and make sure it's clear for others who find this thread:

- https://github.com/advisories/GHSA-g78m-2chm-r7qv relates to _this_ repo, which contains the npm package named `websocket-extensions`. The latest version, containing the fix for this CVE, is 0.1.4.
- https://github.com/advisories/GHSA-g6wq-qcwm-j5g2 relates to https://github.com/faye/websocket-extensions-ruby, which contains the Rubygems package named `websocket-extensions`. The latest version, containing the fix for this CVE, is 0.1.5.
